In [1]:
import numpy as np

In [2]:
x = np.arange(6).reshape(2, 3)

In [3]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
np.putmask(x, x>2, x**2)

In [5]:
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [6]:
x = np.arange(5)

In [7]:
x

array([0, 1, 2, 3, 4])

In [8]:
np.putmask(x, x>1, [-33, -44])

In [9]:
x

array([  0,   1, -33, -44, -33])